version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
  postgres:
    image: postgres:13.3-alpine
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
