DROP TYPE IF EXISTS user_role_type CASCADE;
DROP TABLE IF EXISTS user CASCADE;

DROP TABLE IF EXISTS task CASCADE;

DROP TABLE IF EXISTS team CASCADE;

DROP TABLE IF EXISTS submission CASCADE;

DROP TABLE IF EXISTS user_team CASCADE;